-- AlterTable
ALTER TABLE "contacts" ADD COLUMN     "county" TEXT,
ADD COLUMN     "employer2_monthly_income" DOUBLE PRECISION,
ADD COLUMN     "employer2_months" INTEGER,
ADD COLUMN     "employer2_name" TEXT,
ADD COLUMN     "employer2_phone" TEXT,
ADD COLUMN     "employer2_years" INTEGER,
ADD COLUMN     "employer_months" INTEGER,
ADD COLUMN     "employment2_type" TEXT,
ADD COLUMN     "employment_type" TEXT,
ADD COLUMN     "income2_type" TEXT,
ADD COLUMN     "income_type" TEXT,
ADD COLUMN     "length_at_address_months" INTEGER,
ADD COLUMN     "length_at_address_years" INTEGER,
ADD COLUMN     "middle_name" TEXT,
ADD COLUMN     "name_suffix" TEXT,
ADD COLUMN     "nickname" TEXT,
ADD COLUMN     "prev_city" TEXT,
ADD COLUMN     "prev_county" TEXT,
ADD COLUMN     "prev_length_months" INTEGER,
ADD COLUMN     "prev_length_years" INTEGER,
ADD COLUMN     "prev_rent_mortgage" DOUBLE PRECISION,
ADD COLUMN     "prev_residence_type" TEXT,
ADD COLUMN     "prev_state" TEXT,
ADD COLUMN     "prev_street" TEXT,
ADD COLUMN     "prev_zip" TEXT,
ADD COLUMN     "rent_mortgage" DOUBLE PRECISION,
ADD COLUMN     "residence_type" TEXT,
ADD COLUMN     "salutation" TEXT;

